### PR TITLE
Add support for Swift 5.3

### PR DESCRIPTION
**Pull request by mattt**
Retargeted from #8. See https://github.com/NSHipster/SwiftSyntaxHighlighter/pull/8#issuecomment-698512685

### CODE REVIEW

**Comment by mattt** [comment]
Well, that didn't help. https://github.com/NSHipster/SwiftSyntaxHighlighter/pull/9/checks?check_run_id=1162106566#step:5:145

I'll continue to look for other ways to debug this. Linux support for 5.3 is a blocker for the next release of `swift-doc`.

**Comment by mattt** [comment]
I'll tell you what, [Codespaces](https://github.com/features/codespaces) is really something else. With a little effort, I was able to run and debug the Linux test bundle, and after a bit of trial and error, I was able to trace the error back to `CommandTests` — specifically, this line:

https://github.com/NSHipster/SwiftSyntaxHighlighter/blob/a8a92e5db3c4a710036b47d24a5fc9b98901582a/Tests/SwiftSyntaxHighlighterTests/CommandTests.swift#L18

Screen Shot 2020-09-24 at 12 32 07

Looking back at the logs, I could have figured that out from the information available, but tightening up the feedback loop with an interactive terminal and debugger got me there pretty quick. 

Generating `LinuxMain.swift` and `XCTestManifests.swift` instead of running with `--enable-test-discovery` gives us an easy way to ignore the problematic tests for now. My priority is to remove this blocker for `swift-doc`; we can revisit with a proper fix at some point down the road.

**Comment by MaxDesiatov** [comment]
Thanks for the overview, this is great! Did you set up your Codespaces environment from scratch? I tried to use it previously, but was a bit disappointed there were no popular pre-made Codespace definitions for Swift.

**Comment by mattt** [comment]
@MaxDesiatov I adapted my setup from [this PR](https://github.com/microsoft/vscode-dev-containers/pull/356/files). For the debug setup, I followed [this article](https://www.vknabel.com/pages/Debugging-Swift-in-VS-Code/) by @vknabel (Vielen dank!). 

Coming away from this first real experience with Codespaces, I feel like I have a ton of backlog documentation about VSCode to read in order to understand how everything really works, and how to make the most of it next time.

**Pull request merged**
