### PR TITLE
Test on Linux with Swift 5.3, bump SwiftSyntax

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Review by mattt — APPROVED** [review]

**Comment by mattt** [comment]
@MaxDesiatov Nice! Just waiting for the ✅ from CI. (So nice to finally have an official SwiftSyntax tag for 5.3)

**Comment by mattt** [comment]
@MaxDesiatov Thanks for trying to get backwards compatibility to work. For this dependency, I'd be very happy to drop support for 5.2 with a new major / minor version.

**Comment by MaxDesiatov** [comment]
That crash on Linux is quite puzzling.
At first I though that it's related to the lack of the libxml package that swift-doc CI config installs, but that doesn't seem to make any difference. 🤔

**Comment by mattt** [comment]
@MaxDesiatov Yeah, I was confused by that too. "Exited with signal code 4" makes me think that it's an assertion failure for a failing force unwrap. But I don't know why we aren't getting a backtrace in the logs...

<ins>Edit:</ins> Wait, I think I know why. https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging

<ins>Edit 2:</ins> Or yeah, maybe it's because we're testing in release mode. IIRC, I had it set up that way to avoid any dev/prod issues with the distributed executable.

**Comment by MaxDesiatov** [comment]
Testing with debug builds didn't help `¯\_(ツ)_/¯`

Anyway, I'm off for today, I hope I'll be able to have a closer look in the next few days. Thanks for reviewing these PRs!

**Comment by mattt** [comment]
@MaxDesiatov Same here. Thanks again for all of your help! It's been fun hacking on this together.

**Comment by mattt** [comment]
@MaxDesiatov According to GitHub, "Secrets are not passed to workflows that are triggered by a pull request from a fork." [[1](https://docs.github.com/en/actions/reference/encrypted-secrets)], so I don't think `ACTIONS_STEP_DEBUG` is being set. I'm  retargeting this PR to a new `swift-5.3` branch in this repo so that we can get some visibility into what's causing CI to fail on Linux.

**Pull request merged**
